import { StyleSheet } from 'react-native-unistyles';

export const styles = StyleSheet.create(theme => ({
  card: {
    position: 'absolute',
    top: 0,
    left: 0,
    borderWidth: 7,
    borderColor: theme.colors.white,
    overflow: 'visible',
  },
  decoClip: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    borderRadius: theme.rf(24),
    overflow: 'hidden',
  },
  deco: {
    position: 'absolute',
  },
  cardFront: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    padding: 30,
  },
  cardBack: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    padding: 30,
  },
  cardTitle: {
    fontFamily: theme.typography.primary.medium,
    fontSize: theme.rf(28),
    fontWeight: '500',
    letterSpacing: -0.33,
    color: theme.colors.primary,
  },
  backCardTitle: {
    fontFamily: theme.typography.primary.medium,
    fontSize: theme.rf(16),
    fontWeight: '500',
    lineHeight: theme.rf(16),
    letterSpacing: -0.176,
    color: theme.colors.primary60,
  },
  pill: {
    alignSelf: 'flex-start',
    backgroundColor: '#6CA2DF',
    borderRadius: theme.rf(32),
    paddingHorizontal: theme.rf(16),
    paddingVertical: theme.rf(6),
    marginTop: theme.rf(8),
  },
  pillText: {
    fontFamily: theme.typography.primary.medium,
    fontSize: theme.rf(27),
    fontWeight: '500',
    lineHeight: theme.rf(27),
    letterSpacing: -0.297,
    color: theme.colors.white,
  },
  cardDesc: {
    fontFamily: theme.typography.primary.normal,
    fontSize: theme.rf(14),
    lineHeight: theme.rf(18),
    letterSpacing: -0.154,
    color: theme.colors.primary50,
    marginTop: theme.rf(14),
    maxWidth: '56%',
  },
  dots: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: theme.rf(6),
    marginTop: theme.rf(16),
  },
  dot: {
    width: theme.rf(8),
    height: theme.rf(8),
    borderRadius: theme.rf(4),
    backgroundColor: theme.colors.primary24,
  },
  dotActive: {
    width: theme.rf(26),
    backgroundColor: theme.colors.primary,
  },
  star: {
    position: 'absolute',
    top: theme.rf(-14),
    left: theme.rf(-6),
    zIndex: 5,
  },
  illoWrap: {
    position: 'absolute',
  },
}));
