import { StyleSheet } from 'react-native-unistyles';

export const styles = StyleSheet.create(theme => ({
  card: {
    width: theme.rw(280),
    height: theme.rh(315),
    borderRadius: theme.rf(32),
    padding: theme.rf(16),
    overflow: 'hidden',
  },
  bgVector: {
    position: 'absolute',
    right: theme.rw(-49),
    bottom: theme.rh(0),
  },
  topRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  iconCircle: {
    width: theme.rf(44),
    height: theme.rf(44),
    borderRadius: theme.rf(24),
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: theme.colors.white,
  },
  metaRow: {
    flexDirection: 'row',
    gap: theme.rf(8),
  },
  metaPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: theme.rf(4),
    height: theme.rf(36),
    paddingHorizontal: theme.rf(12),
    borderRadius: theme.rf(24),
    backgroundColor: theme.colors.white17,
  },
  metaText: {
    fontFamily: theme.typography.primary.medium,
    fontSize: theme.rf(10),
    fontWeight: '600',
    letterSpacing: -0.11,
    color: theme.colors.primary50,
  },
  category: {
    fontFamily: theme.typography.primary.normal,
    fontSize: theme.rf(14),
    fontWeight: '400',
    letterSpacing: -0.154,
    color: theme.colors.lilac,
    marginTop: theme.rf(16),
  },
  title: {
    width: theme.rw(201),
    fontFamily: theme.typography.primary.medium,
    fontSize: theme.rf(28),
    fontWeight: '500',
    letterSpacing: -0.308,
    color: theme.colors.ink,
    marginTop: theme.rf(4),
  },
  illoWrap: {
    position: 'absolute',
  },
  startBtn: {
    position: 'absolute',
    left: theme.rw(12),
    right: theme.rw(12),
    bottom: theme.rh(12),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderRadius: theme.rf(64),
    overflow: 'hidden',
    paddingVertical: theme.rf(10),
    paddingLeft: theme.rf(22),
    paddingRight: theme.rf(10),
  },
  startText: {
    fontFamily: theme.typography.primary.bold,
    fontSize: theme.rf(18),
    fontWeight: '600',
    lineHeight: theme.rf(24),
    letterSpacing: -0.198,
    color: theme.colors.primary,
  },
  playCircle: {
    width: theme.rf(40),
    height: theme.rf(40),
    borderRadius: theme.rf(20),
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: theme.colors.primary,
  },
  playIcon: {
    marginLeft: 2,
  },
}));
