import { StyleSheet } from 'react-native-unistyles';

export const styles = StyleSheet.create(theme => ({
  screenContent: {
    padding: 16,
  },
  detailsButtonWrapper: {
    marginTop: theme.spacing.xl,
  },

  // ---- Header ----
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: theme.rf(10),
    flex: 1,
  },
  avatar: {
    width: theme.rf(48),
    height: theme.rf(48),
    borderRadius: theme.rf(24),
  },
  greetCol: {
    flexShrink: 1,
  },
  hello: {
    fontFamily: theme.typography.primary.medium,
    fontSize: theme.rf(13),
    fontWeight: '500',
    lineHeight: theme.rf(20),
    letterSpacing: -0.143,
    color: theme.colors.primary50,
  },
  greeting: {
    fontFamily: theme.typography.primary.medium,
    fontSize: theme.rf(15),
    fontWeight: '500',
    lineHeight: theme.rf(22),
    letterSpacing: -0.165,
    color: theme.colors.primary,
    marginTop: 2,
  },
  headerRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: theme.rf(10),
  },
  langPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: theme.rf(5),
    paddingVertical: theme.rf(12),
    paddingLeft: theme.rf(12),
    paddingRight: theme.rf(16),
    borderRadius: theme.rf(28),
    backgroundColor: theme.colors.surfaceChip,
  },
  langFlagWrap: {
    width: theme.rf(20),
    height: theme.rf(20),
    borderRadius: theme.rf(10),
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
  },
  langFlag: {
    fontSize: theme.rf(20),
    lineHeight: theme.rf(20),
    textAlign: 'center',
    includeFontPadding: false,
  },
  langText: {
    fontFamily: theme.typography.primary.medium,
    fontSize: theme.rf(13),
    color: theme.colors.primary,
  },
  bellBtn: {
    width: theme.rf(48),
    height: theme.rf(48),
    borderRadius: theme.rf(28),
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F3F5F7',
  },
  bellDot: {
    position: 'absolute',
    top: theme.rf(14),
    right: theme.rf(15),
    width: theme.rf(7),
    height: theme.rf(7),
    borderRadius: theme.rf(4),
    backgroundColor: theme.colors.red,
  },

  // ---- Today's pick card ----
  card: {
    backgroundColor: '#E8EBF7',
    borderRadius: theme.rf(32),
    padding: theme.rf(5),
    marginTop: theme.spacing.lg,
    overflow: 'visible',
  },
  decoClip: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    borderRadius: theme.rf(40),
    overflow: 'hidden',
  },
  deco: {
    position: 'absolute',
    bottom: theme.rf(-100),
    right: theme.rf(20),
    width: theme.rw(300),
    height: theme.rw(244),
  },
  banner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: theme.rf(12),
    padding:theme.rf(14),
  },
  bannerText: {
    flex: 1,
  },
  buddyLabel: {
    fontFamily: theme.typography.primary.normal,
    fontSize: theme.rf(12),
    fontWeight: '400',
    letterSpacing: -0.132,
    color: theme.colors.primary50,
  },
  buddyMessage: {
    fontFamily: theme.typography.primary.medium,
    fontSize: theme.rf(14),
    fontWeight: '500',
    letterSpacing: -0.154,
    color: theme.colors.primary,
    marginTop: 2,
  },
  illustration: {
    position: 'absolute',
  bottom: theme.rf(70),
    right: theme.rf(8),
    transform: [{ rotate: '-7.35deg' }],
  },
  bulb: {
    position: 'absolute',
    top: theme.rf(28),
    right: theme.rf(4),
    width: 64,
    height: 64,
    transform: [{ rotate: '56.58deg' }],
  },
  chipsContainer: {
    gap: theme.rf(8),
    bottom: theme.rf(8),
    marginTop: theme.rf(16),
  },
  pick: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#FFFFFFD6',
    borderRadius: theme.rf(32),
    paddingVertical: theme.rf(16),
    paddingHorizontal: theme.rf(14),
    marginTop: theme.rf(18),
  },
  pickLeft: {
    flex: 1,
    paddingRight: theme.rf(12),
  },
  pickTitle: {
    fontFamily: theme.typography.primary.medium,
    fontSize: theme.rf(14),
    fontWeight: '500',
    letterSpacing: -0.154,
    color: theme.colors.primary,
  },
  pickMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: theme.rf(5),
    marginTop: theme.rf(7),
  },
  metaText: {
    fontFamily: theme.typography.primary.medium,
    fontSize: theme.rf(12),
    fontWeight: '500',
    letterSpacing: -0.132,
    color: theme.colors.primary50,
  },
  metaDot: {
    fontFamily: theme.typography.primary.normal,
    fontSize: theme.rf(12),
    color: theme.colors.primary40,
    marginHorizontal: 2,
  },
  pickRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: theme.rf(10),
  },
  completeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
  },
  completeNum: {
    fontFamily: theme.typography.primary.normal,
    fontSize: theme.rf(12),
    fontWeight: '400',
    letterSpacing: -0.132,
    color: theme.colors.primary,
  },
  completeLabel: {
    fontFamily: theme.typography.primary.normal,
    fontSize: theme.rf(12),
    fontWeight: '400',
    letterSpacing: -0.132,
    color: theme.colors.primary50,
  },
  playBtn: {
    width: 48,
    height: 48,
    alignItems: 'center',
    justifyContent: 'center',
  },
  playIcon: {
    position: 'absolute',
    marginLeft: 2,
  },

  // ---- Let's learn section ----
  learnTitle: {
    fontFamily: theme.typography.primary.medium,
    fontSize: theme.rf(24),
    color: theme.colors.primary,
    marginTop: theme.rf(20),
  },
  bleedList: {
    marginHorizontal: -16,
  },
  chipsContent: {
    gap: theme.rf(8),
  },
  chip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: theme.rf(8),
    paddingVertical: theme.rf(5),
    paddingLeft: theme.rf(8),
    paddingRight: theme.rf(5),
    borderRadius: theme.rf(22),
  },
  chipNoIcon: {
    paddingLeft: theme.rf(16),
  },
  chipActive: {
    backgroundColor: theme.colors.primary,
  },
  chipInactive: {
    backgroundColor: theme.colors.transparent,
    borderWidth: 1.5,
    borderColor: theme.colors.primary12,
  },
  chipIcon: {
    width: theme.rf(30),
    height: theme.rf(30),
    borderRadius: theme.rf(15),
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F2F4F8',
  },
  chipLabel: {
    fontFamily: theme.typography.primary.medium,
    fontSize: theme.rf(12),
    fontWeight: '500',
    lineHeight: theme.rf(18),
    letterSpacing: -0.132,
    textAlign: 'center',
    color: theme.colors.primary,
  },
  chipLabelActive: {
    color: theme.colors.white,
  },
  chipCount: {
    width: theme.rf(34),
    height: theme.rf(34),
    borderRadius: theme.rf(40),
    alignItems: 'center',
    justifyContent: 'center',
  },
  chipCountActive: {
    backgroundColor: theme.colors.white,
  },
  chipCountInactive: {
    backgroundColor: theme.colors.primary08,
  },
  chipCountText: {
    fontFamily: theme.typography.primary.medium,
    fontSize: theme.rf(12),
    fontWeight: '500',
    lineHeight: theme.rf(18),
    letterSpacing: -0.132,
    textAlign: 'center',
    color: theme.colors.primary50,
  },
  chipCountTextActive: {
    color: theme.colors.primary,
  },
  cardsContent: {
    paddingHorizontal: 16,
    gap: 0,
    paddingTop: theme.rf(14),
    paddingBottom: theme.rf(8),
  },
}));
